# 01-init.yml
# ansible-playbook 01-init.yaml -i inventory/hosts.ini
---
- hosts: bitcoin
  gather_facts: no
  become: yes
  vars_prompt:
    - name: DEFAULT_PASSWORD
      prompt: "Enter default user password"
      private: yes
      default: "password"
  roles:
    - role: secure