# 03-install.yml
# ansible-playbook 03-install.yaml -i inventory/hosts.ini
---
- hosts: bitcoin
  gather_facts: no
  become: yes
  # vars_prompt:
  #   - name: DEFAULT_PASSWORD
  #     prompt: "Enter default user password"
  #     private: yes
  #     default: "password"
  roles:
    - role: tor