- name: "Create directory {{ SSD_MOUNT_POINT }} to mount external drive"
  file:
    path: "{{ SSD_MOUNT_POINT }}"
    state: directory

- name: Get the UUID of the external drive
  delegate_facts: true
  shell: | 
    blkid /dev/sda1 | awk -F'"' '{print $2}'
  register: uuid

- name: Mount external drive by UUID
  ansible.posix.mount:
    src: "UUID={{uuid.stdout}}"
    path: "{{ SSD_MOUNT_POINT }}"
    fstype: ext4
    opts: rw,nosuid,dev,noexec,noatime,nodiratime,auto,nouser,async,nofail
    dump: 0
    passno: 2
    state: mounted

- name: "Create bitcoin node directory at {{ SSD_MOUNT_POINT }}"
  file:
    path: "{{ NODE_DIR }}"
    state: directory
    owner: "{{ DEFAULT_USER }}"
    group: "{{ DEFAULT_USER }}"
    mode: u+rw,g+r,o+r