---
- name: Upgrade the OS (apt-get dist-upgrade)
  ansible.builtin.apt:
    update_cache: yes 
    upgrade: dist

- name: Update installed packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: yes

## References
## https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html